# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18d80c909cbc442ca9a04b337ab8e6cac5ae6fce38f92c79085f0f3904a8a5d5c639f962b5dda4a6363f0499047f573b73a2781bc14cbe8aefb574b57a3a5e04

test:
  secret_key_base: 408ef19306bce7e85e2527a75c9db5b42fe922ff7ed8eaed38bb81540a146b9fc6e33c4af631ff682790c73fed3905e5a7686d83b8b3c9f55fe4ff37029bab38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
